### PR TITLE
Doc new ngon layout

### PR DESCRIPTION
**Pull request by MicK7**
The documentation for SIDS, file mapping and MLL is updated according to CPEX0041.

### CODE REVIEW

**Comment by brtnfld** [comment]
Can you fix the conflicts? The develop branch was not in sync with master. It is now, hence the conflicts.

The master version is probably the correct one.

**Comment by MicK7** [comment]
The conflicts should be fixed as well as the typo.

**Comment by crumsey** [comment]
Thanks.  One more minor thing in the latex doc files:  intro.tex should be updated with a brief Section on changes made for V3.4.  It can be very simple.  For example:  ‘Added ElementStartOffset for Mixed, Ngon_n, and Nface_n elements, from CPEX 0041’

**Comment by MicK7** [comment]
Thanks for the feedback. The new section is created.

**Pull request merged**
